import pandas as pd
import matplotlib.pyplot as plt
import sys
import numpy as np

def histogram(bin_width):
    try:
        # load the data generated by the C++ program
        data = pd.read_csv('outputfile.csv', header=None, names=['size'])
        
        if data.empty:
            print("No data found in file_sizes.csv.?")
            return

        max_size = data['size'].max()
        
        # create bins based on the user-specified width
        bins = np.arange(0, max_size + bin_width, bin_width)

        plt.figure(figsize=(10, 6))
        plt.hist(data['size'], bins=bins, edgecolor='black', alpha=0.7, color='skyblue')
        
        plt.title(f'File Size Distribution\n(Bin Width: {bin_width} bytes)')
        plt.xlabel('File Size (Bytes)')
        plt.ylabel('Number of Files')
        plt.grid(axis='y', linestyle='--', alpha=0.7)
        
        # save histogram to png file
        output_file = 'histogram.png'
        plt.savefig(output_file)
        print(f"Histogram saved as {output_file}")

    # check for errors
    except FileNotFoundError:
        print("Error: 'file_sizes.csv' not found. Run the C++ 'filesystem' program first.")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

if __name__ == "__main__":
    # get bin width from command line argument, default to 1024
    try:
        width = int(sys.argv[1]) if len(sys.argv) > 1 else 1024
        histogram(width)
    except ValueError:
        print("Error: Bin width must be an integer.")